// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/syncverse/Atlas.tsx": () => import("../components/mockups/syncverse/Atlas.tsx"),
  "./components/mockups/syncverse/Beacon.tsx": () => import("../components/mockups/syncverse/Beacon.tsx"),
  "./components/mockups/syncverse/Pulse.tsx": () => import("../components/mockups/syncverse/Pulse.tsx")
};
